name: Push to GCR GitHub Action Fazpass Docs Production
on:
  push:
    branches:
      - "master"

env:
  REGISTRY: asia.gcr.io
  REGISTRY_NAME: fazpass-docs
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SHA: ${GITHUB_SHA}

jobs:
  build-and-push-producton:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set version tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: ${{ env.REGISTRY }}
          project_id: ${{ env.PROJECT_ID }}
          image_name: ${{ env.REGISTRY_NAME }}
          dockerfile: ./Dockerfile
          image_tag: latest,${{ steps.vars.outputs.sha_short }}


