name: Push Fazpass Docs
on:
  push:
    branches:
      - "main"

env:
  REGISTRY_NAME: fazpass-docs
  SHA: ${GITHUB_SHA}

jobs:
  build-and-push-producton:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set version tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: fazpass/gupi/vault/kv@main
        name: import-secrets
        with:
          vault_url: ${{ secrets.vault_url }}
          vault_username: ${{ secrets.vault_username }}
          vault_password:  ${{ secrets.vault_password }}
          secrets: |
            github-actions/data/general * ;

      - uses: fazpass/gupi/docker@main
        with: 
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - uses: fazpass/gupi/be@v0.0.4
        with:
          gcloud_service_key: ${{ env.GCLOUD_SERVICE_KEY }}
          registry: ${{ env.REGISTRY }}
          project_id: ${{ env.PROJECT_ID }}
          image_name: ${{ env.REGISTRY_NAME }}
          dockerfile: ./Dockerfile
          image_tag: latest,${{ steps.vars.outputs.sha_short }}
